const ReduxTypes = {
  INIT: '@@REDUX_COMMON/INIT',
  INIT_DONE: '@@REDUX_COMMON/INIT_DONE',
  RESET: '@@REDUX_COMMON/RESET',
  RESET_FILTERS: '@@REDUX_COMMON/RESET_FILTERS',
  UPDATE_FILTER: '@@REDUX_COMMON/UPDATE_FILTER',
  UPDATE_SEARCH_QUERY: '@@REDUX_COMMON/UPDATE_SEARCH_QUERY',
  ON_SCROLL: '@@REDUX_COMMON/ON_SCROLL',

  GET_LIST: '@@REDUX_COMMON/GET_LIST',
  GET_LIST_DONE: '@@REDUX_COMMON/GET_LIST_DONE',

  GET_DETAIL: '@@REDUX_COMMON/GET_DETAIL',
  GET_DETAIL_DONE: '@@REDUX_COMMON/GET_DETAIL_DONE',

  CREATE: '@@REDUX_COMMON/CREATE',
  CREATE_DONE: '@@REDUX_COMMON/CREATE_DONE',

  UPDATE: '@@REDUX_COMMON/UPDATE',
  UPDATE_DONE: '@@REDUX_COMMON/UPDATE_DONE',

  DELETE: '@@REDUX_COMMON/DELETE',
  DELETE_DONE: '@@REDUX_COMMON/DELETE_DONE',

  UPDATE_VALUE: '@@REDUX_COMMON/UPDATE_VALUE',
  ADD_NOTI: '@@REDUX_COMMON@@DASHBOARD@@ADD_NOTI',
  REMOVE_NOTI: '@@REDUX_COMMON@@DASHBOARD@@REMOVE_NOTI',
};

const ReduxTableTypes = {
  TABLE_INIT: '@@REDUX_COMMON@@TABLE_INIT',
  ON_SORT: '@@REDUX_COMMON@@TABLE_SORT',
  ON_PAGINATION: '@@REDUX_COMMON@@TABLE_PAGINATION',
  ON_SELECT_ROW: '@@REDUX_COMMON@@TABLE_SELECT_ROW',
  ON_RESET_SELECT_ROW: '@@REDUX_COMMON@@ON_RESET_SELECT_ROW',
  ON_SELECT_ALL_ROW: '@@REDUX_COMMON@@TABLE_SELECT_ALL_ROW',
  RESET_PAGING: '@@REDUX_COMMON@@TABLE_RESET_PAGING',
  ON_SELECT_ALL: '@@REDUX_COMMON@@TABLE_SELECT_ALL',
  ON_SELECT_ALL_IN_PAGE: '@@REDUX_COMMON@@ON_SELECT_ALL_IN_PAGE',
  ON_TABLE_SUB_ROW: '@@REDUX_COMMON@@ON_TABLE_SUB_ROW',
  ON_UPDATE_IS_COLUMNS_LOADED: '@@REDUX_COMMON@@ON_UPDATE_IS_COLUMNS_LOADED',
};

export default ReduxTypes;
export { ReduxTableTypes };
